name: Add to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          project-url: https://github.com/users/oliverfoster/projects/2
          github_token: ${{ secrets.SECRET_TOKEN }}
